### PR TITLE
Refactor Controller creation so that it can be tested

### PR DESCRIPTION
**Pull request by wallrj**
* A new public function for creating a controller from a context
* Modify the integration test to use that.
* Refactor the integration test to use its own fixture which hopefully makes the test a little clearer.
* ...and improves the orderly shutdown of controller, event watcher / logger and informers etc.

Part of: https://gitlab.jetstack.net/marshal/navigator/issues/26

You can test this using

```
go test -run TestCassandraControllerIntegration -v  ./pkg/controllers/... -args -v 100 -alsologtostderr
```

```release-note
NONE
```

### CODE REVIEW

**Comment by munnerz** [comment]
@wallrj rebase needed 😄

**Comment by munnerz** [comment]
... looks like something went weird with the bot and it didn't already tell us this....

**Comment by munnerz** [comment]
/lgtm

@wallrj if you're happy with this, /approve when you are ready!

**Comment by munnerz** [comment]
.... well the regex for `/approve` is more lax than I thought!

**Comment by wallrj** [comment]
Haha. Yeah I noticed that. Thanks.

**Pull request merged**
