### PR TITLE
Rely on externally provisioned cluster for e2e tests

### PR DESCRIPTION
**Pull request by munnerz**
**What this PR does / why we need it**:

Switches us to take advantage of https://github.com/jetstack/test-infra/pull/79 - where the minikube vm is provisioned by some external source.

**Release note**:
```release-note
NONE
```

/assign

### CODE REVIEW

**Comment by munnerz** [comment]
@wallrj I'm going to merge this now as I have merged the changes in test-infra.

**Comment by wallrj** [comment]
What's the advantage of this?
Are you working on something to provision non-minikube clusters?
Builds still failing: https://jetstack-build-infra.appspot.com/build/jetstack-logs/pr-logs/pull/jetstack_navigator/143/navigator-e2e-v1-8/161/ with errors like:

```
W1123 10:02:43.602] The connection to the server 192.168.42.29:8443 was refused - did you specify the right host or port?
W1123 10:02:43.603] + kubectl logs -c apiserver -l app=navigator,component=apiserver
W1123 10:02:43.603] + egrep '^E[0-9]{4} '
W1123 10:02:43.690] The connection to the server 192.168.42.29:8443 was refused - did you specify the right host or port?
W1123 10:02:43.697] + kubectl api-versions
W1123 10:02:43.807] error: Couldn't get available api versions from server: Get https://192.168.42.29:8443/api: dial tcp 192.168.42.29:8443: getsockopt: connection refused

```

**Comment by munnerz** [comment]
Reason for this is to remove the onus on provisioning a cluster from individual projects and centralised into our testing infra. This will allow us to use the same scenarios for cert-manager as well as navigator, and more easily test additional k8s versions (as they can all be provisioned by test-infra, so is no longer navigators concern).

Regarding test failures - that's something to look into. This PR (and others) have been passing. Have you rebased PR #143 on the latest master to include the changes in this PR?

**Pull request merged**
