### PR TITLE
Add shortName for cassandracluster

### PR DESCRIPTION
**Pull request by kragniz**
So commands like `kubectl get cass` are shorter.

```release-note
none
```

### CODE REVIEW

**Comment by wallrj** [comment]
I've got mixed feelings about this.
* I'm not a fan of short names....I think they make shell scripts unclear, and kubectl command line completion takes away the pain of typing out the full name.
* Perhaps I'd suggest `kubectl get cassandra`
* But happy to go with this if others are in favour.
* What ever we choose let's use both short and long forms in the E2E tests, so that we can see it working.
* A simple `kubectl get cass` at the start of the test would be sufficient.

**Comment by munnerz** [comment]
`kubectl get cassandra` feels more natural and sets a precedent for how we shorten names in future (e.g. `CouchbaseCluster` -> `couchbase`) etc.

I'm not bothered about `cass` too much, but it does seems to be an arbitrarily shortened version of `cassandra` and isn't particularly obvious. wdyt @kragniz?

**Comment by kragniz** [comment]
`cass` was pretty random, I'm happy with `cassandra` instead.

**Comment by munnerz** [comment]
ping @kragniz

**Comment by kragniz** [comment]
Updated with `cassandra` and `elasticsearch` shortnames

**Pull request merged**
